config/routes.rb
Rails.application.routes.draw do
  
  resources :administradors
  resources :pedidos do 
    resources :pedido_produtos
  end
  resources :clientes
  resources :produtos
  resources :tipo_produtos
  
  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/sair', to: 'login#sair'
  get '/home', to: 'home#index'

  get '/produto/:produto_id', to: 'ecommerce#index'
  get '/produto/:produto_id/adicionar', to: 'ecommerce#adicionar'
  get '/produto/:produto_id/remover', to: 'ecommerce#remover'
  get '/carrinho', to: 'ecommerce#carrinho'
  get '/carrinho/fechar', to: 'ecommerce#fechar_carrinho'
  get '/cliente/logar', to: 'ecommerce#login'
  post '/cliente/login', to: 'ecommerce#fazer_login_cliente'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  get '/cliente/cadastrar', to: 'ecommerce#cadastrar'
  post '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/criar', to: 'ecommerce#cadastrar_cliente'
  patch '/cliente/compra-concluida', to: 'ecommerce#/compra_concluida'
  patch '/cliente/seu-boleto', to: 'ecommerce#/boleto_gerado'
  get '/cliente/sair', to: 'ecommerce#sair'
  post '/cliente/concluir-pagamento', to: 'ecommerce#concluir_pagamento'
  get '/cliente/pagamento', to: 'ecommerce#confirmar_pagamento'
  
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :nome, :cpf, :telefone, :senha, :email, presence: true

  def nome_tratado
    nome = self.nome.split(" ").first
  end

  def sobrenome
    nome = self.nome.split(" ").first
    sobrenome = self.nome.split(" ").last
    return "" if nome == sobrenome
    sobrenome
  end 
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :telefone, :email, :cep, :endereco, :numero, :bairro, :cidade, :estado, :senha)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Verfique os erros abaixo</h4>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cpf,"CPF", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cpf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cep, "CEP", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cep, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :endereco, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :endereco, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :numero, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :numero, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bairro, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :bairro, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :estado, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :estado, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="page-header">
  <%= link_to new_cliente_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Cliente
  <% end %>
  <h1>Lista clientes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Telefone</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <%# <th></th> %>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clientes) do |cliente| %>
        <td><%=  link_to cliente.nome, cliente %></td>
        <td><%= link_to cliente.cpf, cliente %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.email %></td>
        <%#= link_to 'Mostrar', cliente %>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clientes/new.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/show.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostar cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @cliente.nome %></dd>

  <dt>CPF:</dt>
  <dd><%= @cliente.cpf %></dd>

  <dt>Telefone:</dt>
  <dd><%= @cliente.telefone %></dd>

  <dt>Email:</dt>
  <dd><%= @cliente.email %></dd>
  <hr>
  <dt>CEP:</dt>
  <dd><%= @cliente.cep %></dd>

  <dt>Endereco:</dt>
  <dd><%= @cliente.endereco %></dd>

  <dt>Numero:</dt>
  <dd><%= @cliente.numero %></dd>

  <dt>Bairro:</dt>
  <dd><%= @cliente.bairro %></dd>

  <dt>Cidade:</dt>
  <dd><%= @cliente.cidade %></dd>

  <dt>Estado:</dt>
  <dd><%= @cliente.estado %></dd>

</dl>